"use strict";

/**
 * Regenerate the partition's GENERATED VIEWS for the sweep — WITHOUT regenerating the committed framework manifests.
 *
 * The occurrence register's `derived` warrant claims a property of the REGENERATED bytes ("permitted iff it
 * corresponds to a Class-3 pin, asserted after manifest regen"). Sweeping the committed (possibly stale) bytes would
 * make `derived` an unchecked absolution. So the builders are run — but in a THROWAWAY clone checked out at the
 * measured commit, never in the measured worktree. The committed `.claude/framework-manifest.json`,
 * `.claude/framework-installed.json`, `_mc/MANIFEST.json`, `.claude/paths.json` and
 * `scripts/hooks/lib/paths.generated.js` are never written; the clone is deleted after its bytes are read.
 *
 * The separation is by OUTPUT LOCATION: same builders, same order as release-canonical.js stage 6
 * (fm -> installed -> fm -> _mc), plus scripts/paths/build.js for the two path views, all rooted in the clone
 * (every builder resolves its ROOT from its own __dirname, so running the clone's copy writes only the clone).
 *
 * Any builder failure, a missing view after regen, or a clone checkout failure is a REFUSAL — the oracle never falls
 * back to the committed bytes.
 */

const fs = require("fs");
const os = require("os");
const path = require("path");
const { spawnSync } = require("child_process");
const { OracleRefusal, git, toPosix, NEEDLE_ALL_RE } = require("./lib");

function countNeedle(text) {
  return (String(text).match(NEEDLE_ALL_RE()) || []).length;
}

/**
 * -> { sha, cloneDir, kept, steps:[{script,args,status,ms}], views: Map(relPath -> regenerated content),
 *      comparison:[{path, committedOcc, regeneratedOcc, bytesIdentical}] }
 */
function regenerateViews({ root, sha, partition, trackedFiles, version, keep = false }) {
  const commonDir = git(root, ["rev-parse", "--path-format=absolute", "--git-common-dir"]);
  if (commonDir.status !== 0) throw new OracleRefusal(`regen: cannot resolve git common dir: ${(commonDir.stderr || "").trim()}`);
  const tmpBase = fs.mkdtempSync(path.join(os.tmpdir(), "s-os-06-r4-regen-"));
  const cloneDir = path.join(tmpBase, "repo");
  const steps = [];
  const cleanup = () => {
    if (keep) return;
    try {
      fs.rmSync(tmpBase, { recursive: true, force: true, maxRetries: 3 });
    } catch {
      /* best-effort temp cleanup; never affects the measurement */
    }
  };
  try {
    const clone = spawnSync(
      "git",
      ["-c", "core.longpaths=true", "clone", "--shared", "--no-checkout", "--quiet", commonDir.stdout.trim(), cloneDir],
      { encoding: "utf8", env: { ...process.env, GIT_TERMINAL_PROMPT: "0" }, maxBuffer: 64 * 1024 * 1024 }
    );
    if (clone.status !== 0) throw new OracleRefusal(`regen: scratch clone failed: ${(clone.stderr || "").trim()}`);
    const co = spawnSync("git", ["-c", "core.longpaths=true", "-c", "core.autocrlf=false", "checkout", "--quiet", "--detach", sha], {
      cwd: cloneDir,
      encoding: "utf8",
      env: { ...process.env, GIT_TERMINAL_PROMPT: "0" },
      maxBuffer: 64 * 1024 * 1024,
    });
    if (co.status !== 0) throw new OracleRefusal(`regen: scratch checkout of ${sha} failed: ${(co.stderr || "").trim()}`);
    const cloneHead = spawnSync("git", ["rev-parse", "HEAD"], { cwd: cloneDir, encoding: "utf8" }).stdout.trim();
    if (cloneHead !== sha) throw new OracleRefusal(`regen: scratch clone HEAD ${cloneHead} != measured ${sha}`);

    const plan = [
      ["scripts/paths/build.js", []],
      ["scripts/generate-framework-manifest.js", []],
      ["scripts/mc/snapshot-installed.js", []],
      ["scripts/generate-framework-manifest.js", []],
      ["scripts/mc/manifest/build.js", ["--mc-version", version]],
    ];
    for (const [script, args] of plan) {
      const t0 = Date.now();
      const r = spawnSync(process.execPath, [path.join(cloneDir, script), ...args], {
        cwd: cloneDir,
        encoding: "utf8",
        maxBuffer: 64 * 1024 * 1024,
        env: { ...process.env, GIT_TERMINAL_PROMPT: "0" },
        timeout: 10 * 60 * 1000,
      });
      steps.push({ script, args, status: r.status, ms: Date.now() - t0 });
      if (r.status !== 0) {
        throw new OracleRefusal(
          `regen: builder ${script} ${args.join(" ")} exited ${r.status}${r.error ? ` (${r.error.message})` : ""}: ${String(r.stderr || r.stdout || "").trim().slice(0, 400)} — the sweep never falls back to committed bytes`
        );
      }
    }

    const trackedSet = new Set(trackedFiles);
    const views = new Map();
    const comparison = [];
    for (const g of partition.generatedViews) {
      const candidates = partition.viewPathCandidates(g).map(toPosix);
      const present = candidates.filter((p) => trackedSet.has(p));
      if (present.length === 0) {
        throw new OracleRefusal(`regen: generated view entry '${g.path}' has no tracked path (candidates: ${candidates.join(", ")})`);
      }
      for (const p of present) {
        const regenAbs = path.join(cloneDir, p);
        if (!fs.existsSync(regenAbs)) throw new OracleRefusal(`regen: view ${p} does not exist after regeneration`);
        const regenerated = fs.readFileSync(regenAbs, "utf8");
        let committed = null;
        try {
          committed = fs.readFileSync(path.join(root, p), "utf8");
        } catch {
          committed = null;
        }
        views.set(p, regenerated);
        comparison.push({
          path: p,
          committedOcc: committed === null ? null : countNeedle(committed),
          regeneratedOcc: countNeedle(regenerated),
          bytesIdentical: committed !== null && committed === regenerated,
          lfNormalizedIdentical: committed !== null && committed.replace(/\r\n/g, "\n") === regenerated.replace(/\r\n/g, "\n"),
        });
      }
    }
    return { sha, cloneDir: toPosix(cloneDir), kept: keep, steps, views, comparison };
  } finally {
    cleanup();
  }
}

function formatRegen(regen) {
  const lines = [];
  lines.push(
    `  GENERATED VIEWS regenerated BEFORE the sweep in a throwaway clone at ${regen.sha.slice(0, 12)} (${regen.kept ? `kept at ${regen.cloneDir}` : "clone deleted after read"}); committed manifests NOT written`
  );
  lines.push(`    builder steps: ${regen.steps.map((s) => `${s.script}${s.args.length ? " " + s.args.join(" ") : ""} -> exit ${s.status} (${s.ms}ms)`).join("; ")}`);
  for (const c of regen.comparison) {
    lines.push(
      `    view ${c.path}: committed-occ=${c.committedOcc} regenerated-occ=${c.regeneratedOcc} bytes-identical=${c.bytesIdentical} (ignoring generatedAt-style fields is NOT applied; lf-normalized-identical=${c.lfNormalizedIdentical})`
    );
  }
  return lines;
}

module.exports = { regenerateViews, formatRegen, countNeedle };
