"use strict";
/**
 * lib/render.js — tiny template renderer + artifact writer for lastmile phases.
 *
 * Templates ship in _mc/templates/lastmile/<basename>.tmpl.md (framework-
 * owned, installed into consumer products). Each template uses a small fixed var
 * set ({{title}}, {{generated_at}}, {{summary}}, {{body}}) so templates stay
 * trivial + stable and the PHASES own the document content. If a template is
 * missing, fillTemplate falls back to a generated doc so the chain never breaks
 * (mirrors canon/generate.js "always emit structurally-valid output").
 */

const fs = require("fs");
const path = require("path");

// scripts/bootstrap/lastmile/lib → repo root is four levels up.
const TEMPLATE_DIR = path.join(__dirname, "..", "..", "..", "..", "_mc", "templates", "lastmile");

function fillTemplate(basename, vars) {
  let tmpl = null;
  try {
    tmpl = fs.readFileSync(path.join(TEMPLATE_DIR, `${basename}.tmpl.md`), "utf8");
  } catch {
    /* missing template — fall back below */
  }
  if (tmpl == null) {
    return (
      `# ${vars.title || basename}\n\n` +
      `> Generated by /bootstrap:lastmile on ${vars.generated_at || ""} (template fallback). ${vars.summary || ""}\n\n` +
      `${vars.body || ""}\n`
    );
  }
  return tmpl.replace(/\{\{(\w+)\}\}/g, (_, k) => (vars[k] != null ? String(vars[k]) : ""));
}

// Write a rendered doc to ctx.outDir (product-side). Returns repo-relative path,
// or null on dry-run.
function writeDoc(ctx, basename, content) {
  if (ctx.dryRun) return null;
  const outDir = path.isAbsolute(ctx.outDir) ? ctx.outDir : path.join(ctx.repoRoot, ctx.outDir);
  fs.mkdirSync(outDir, { recursive: true });
  const f = path.join(outDir, `${basename}.md`);
  fs.writeFileSync(f, content, "utf8");
  return path.relative(ctx.repoRoot, f).split(path.sep).join("/");
}

// Write a doc at an arbitrary repo-relative path (e.g. last-mile-handoff.md at root).
function writeAt(ctx, relPath, content) {
  if (ctx.dryRun) return null;
  const f = path.join(ctx.repoRoot, relPath);
  fs.mkdirSync(path.dirname(f), { recursive: true });
  fs.writeFileSync(f, content, "utf8");
  return relPath;
}

function nowIso() {
  return new Date().toISOString().slice(0, 10);
}

module.exports = { fillTemplate, writeDoc, writeAt, nowIso, TEMPLATE_DIR };
