#!/usr/bin/env node
/**
 * bootstrap-systems.js — Seed paths.systemsFile (.claude/project/memory/systems.jsonl)
 * from the canonical paths.maps/systems-inventory.jsonl rollup plus light disk scans.
 *
 * Why this exists:
 *   ~6 skills and the systems-sync hook expect paths.systemsFile to be a JSONL of
 *   per-system records with shape:
 *     { id, name, description, status, category, files[], depends_on[],
 *       test: { command, last_tested, last_result },
 *       diagnose: { health_check, common_failures[] },
 *       created, last_modified, notes }
 *   But .claude/project/memory/ is gitignored and the file was missing on a fresh
 *   checkout. This script is the deterministic bootstrap.
 *
 * Source of truth:
 *   paths.maps/systems-inventory.jsonl — category rollup (16 entries today).
 *   Each rollup entry maps to one system record. count: N → status starts
 *   "operational" if N>0, "untested" if N=0. Specific files lists are
 *   pulled from the rollup where present and otherwise enumerated from
 *   the live category directory.
 *
 * Re-runnable:
 *   Idempotent — overwrites the target file each run. Status fields like
 *   `test.last_tested` reset to null on rebuild; the systems-sync hook
 *   updates these incrementally during normal work.
 *
 * Run: node scripts/maps/bootstrap-systems.js
 */

const fs = require("fs");
const path = require("path");

const PROJECT = path.resolve(__dirname, "..", "..");
const TODAY = new Date().toISOString().slice(0, 10);

const INVENTORY = path.join(
  PROJECT,
  ".claude",
  "project",
  "maps",
  "systems-inventory.jsonl",
);
const OUT = path.join(PROJECT, ".claude", "project", "memory", "systems.jsonl");

function readJsonl(p) {
  if (!fs.existsSync(p)) return [];
  return fs
    .readFileSync(p, "utf8")
    .split(/\r?\n/)
    .filter((l) => l.trim())
    .map((l) => JSON.parse(l));
}

function walkExt(dir, ext) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  const stack = [dir];
  while (stack.length) {
    const d = stack.pop();
    for (const ent of fs.readdirSync(d, { withFileTypes: true })) {
      const full = path.join(d, ent.name);
      if (ent.isDirectory()) stack.push(full);
      else if (!ext || ent.name.endsWith(ext)) out.push(full);
    }
  }
  return out;
}

function relList(absPaths) {
  return absPaths.map((p) => path.relative(PROJECT, p).replace(/\\/g, "/"));
}

// Map category-rollup id → enrichment metadata for the full system record.
// Anything not enumerated here falls back to a generic descriptor.
const ENRICH = {
  identity: {
    description:
      "Top-level identity and project context — CLAUDE.md (operating system), AGENTS.md (team).",
    depends_on: [],
    test: "Read paths.docsRoot/../CLAUDE.md and verify identity section parses.",
    health: "Both CLAUDE.md and AGENTS.md exist at repo root.",
  },
  agents: {
    description: "Agent team and dispatchable build chains under paths.agents.",
    depends_on: ["identity", "skills", "paths-registry"],
    test: "Run /agents:list and confirm count matches files under paths.agents.",
    health:
      "paths.agents directory exists and contains *.md specs for each registered role.",
    files: () =>
      relList(walkExt(path.join(PROJECT, ".claude", "agents"), ".md")),
  },
  skills: {
    description:
      "Slash-command skills under paths.commands invoked via the Skill tool.",
    depends_on: ["paths-registry"],
    test: "Run /agents:list; cross-check with `node scripts/regen-maps.js` skills count.",
    health:
      "Every *.md under paths.commands has frontmatter (description, allowed-tools).",
  },
  hooks: {
    description: "Lifecycle hooks under paths.hooks wired in paths.settings.",
    depends_on: ["paths-registry"],
    test: "Run /hooks:test or `node scripts/hooks-doctor.js` if present.",
    health:
      "Every hook script in paths.settings exists on disk; no orphan or unregistered file.",
  },
  memory: {
    description:
      "Append-only memory stores under paths.memory + paths.events (events.jsonl, learnings.jsonl, traces.jsonl, etc.).",
    depends_on: ["paths-registry"],
    test: "Tail paths.eventsFile; confirm recent log lines write via logger.js.",
    health:
      "paths.memory and paths.events directories exist; logger lib resolves PATHS keys.",
  },
  maps: {
    description:
      "Relationship and inventory maps under paths.maps regenerated by scripts/regen-maps.js.",
    depends_on: ["skills", "hooks", "memory"],
    test: "Run /maps:all and verify 7 maps regenerate without error.",
    health:
      "All map *.md and *.jsonl files present and not older than 30 days.",
  },
  "paths-registry": {
    description:
      "Centralized paths.json registry — single source of truth for project paths.",
    depends_on: [],
    test: "Run /paths:doctor; verify all paths.* keys resolve to real on-disk locations.",
    health: ".claude/paths.json validates against schemas/paths.schema.json.",
  },
  manifest: {
    description: "Project identity card — paths.manifest.",
    depends_on: ["paths-registry"],
    test: "Run /manifest:validate.",
    health: "paths.manifest exists and matches the manifest schema.",
  },
  settings: {
    description: "Hook + tool settings — paths.settings.",
    depends_on: ["hooks"],
    test: "Run /hooks:test against every entry in settings.json.",
    health: "paths.settings parses and every hook reference resolves.",
  },
  store: {
    description: "Build-chain run store — paths.store.",
    depends_on: ["agents"],
    test: "Run /agents:test; verify dispatch ledger writes to paths.store.",
    health: "paths.store exists and is valid JSON.",
  },
  "spec-graph": {
    description:
      "Requirement → story → AC dependency graph generated at paths.specGraph.",
    depends_on: ["maps", "paths-registry"],
    test: "Run `node scripts/maps/spec-graph.js` and inspect output node/edge counts.",
    health:
      "paths.specGraph exists, non-empty, and has nodes referencing real source files.",
  },
  "reference-docs": {
    description:
      "Reference documentation under paths.reference — long-form rules, lifecycles, lexicon.",
    depends_on: [],
    test: "Run /docs:catalog and verify every reference doc renders.",
    health: "paths.reference directory exists and contains *.md.",
    files: () =>
      relList(
        walkExt(path.join(PROJECT, ".claude", "project", "reference"), ".md"),
      ),
  },
  patterns: {
    description:
      "Engineering patterns library under paths.patterns — reusable code/process patterns.",
    depends_on: [],
    test: "List paths.patterns/*.md and verify each has a one-line summary.",
    health: "paths.patterns directory exists.",
    files: () => relList(walkExt(path.join(PROJECT, "patterns"), ".md")),
  },
  "requirements-templates": {
    description:
      "Sprint and product requirement templates under paths.sprintTemplates.",
    depends_on: [],
    test: "Run /sprint:design --dry-run; templates must render without error.",
    health: "paths.sprintTemplates exists with at least the seven core docs.",
    files: () =>
      relList(
        walkExt(path.join(PROJECT, "_mc", "templates", "sprint"), ".md"),
      ),
  },
  installer: {
    description:
      "MC installer surface — scripts/warp-setup.js, install.ps1, version.json.",
    depends_on: [],
    test: "Run /scan:install on a fresh clone.",
    health: "All three installer entry-points exist and version.json parses.",
  },
  linters: {
    description: "Lint suite — paths-lint plus *-lint-*.js validators.",
    depends_on: [],
    test: "Run /linters:run and verify every linter exits 0 (or known-yellow).",
    health:
      "Every script under scripts/lint-*.js exits with code 0 on a clean tree.",
  },
};

function buildEntry(rollup) {
  const enr = ENRICH[rollup.id] || {};
  // Pick the strongest available file list.
  let files = [];
  if (Array.isArray(rollup.files) && rollup.files.length) {
    files = rollup.files;
  } else if (rollup.path) {
    files = [rollup.path];
  } else if (typeof enr.files === "function") {
    files = enr.files();
  }
  // If we have nothing concrete, fall back to the inventory dir.
  if (!files.length && rollup.dir) files = [rollup.dir];

  const status = (() => {
    if (typeof rollup.count === "number") {
      return rollup.count > 0 ? "operational" : "untested";
    }
    return files.length ? "operational" : "untested";
  })();

  return {
    id: rollup.id,
    name: rollup.name || rollup.id,
    description:
      enr.description ||
      `${rollup.name || rollup.id} — bootstrapped from systems-inventory.jsonl.`,
    status,
    category: rollup.category || "uncategorized",
    files,
    depends_on: enr.depends_on || [],
    test: {
      command:
        enr.test ||
        `Inspect ${rollup.name || rollup.id} and verify it behaves as advertised.`,
      last_tested: null,
      last_result: null,
    },
    diagnose: {
      health_check:
        enr.health ||
        `Confirm ${files.length || (rollup.count ?? 0)} files referenced by ${rollup.id} exist on disk.`,
      common_failures: [],
    },
    created: TODAY,
    last_modified: TODAY,
    notes:
      "Auto-bootstrapped by scripts/maps/bootstrap-systems.js. Schema lives in scripts/hooks/systems-sync.js. paths.systemsFile is the canonical store.",
  };
}

function main() {
  if (!fs.existsSync(INVENTORY)) {
    process.stderr.write(
      `bootstrap-systems: source missing — paths.maps/systems-inventory.jsonl ` +
        `(${INVENTORY}). Run /maps:all first.\n`,
    );
    process.exit(1);
  }

  fs.mkdirSync(path.dirname(OUT), { recursive: true });

  const rollups = readJsonl(INVENTORY);
  const entries = rollups.map(buildEntry);

  // Atomic write — tmp + rename.
  const tmp = OUT + ".tmp";
  fs.writeFileSync(
    tmp,
    entries.map((e) => JSON.stringify(e)).join("\n") + "\n",
  );
  fs.renameSync(tmp, OUT);

  const byStatus = entries.reduce((acc, e) => {
    acc[e.status] = (acc[e.status] || 0) + 1;
    return acc;
  }, {});

  process.stdout.write(
    `bootstrap-systems → wrote ${entries.length} entries to paths.systemsFile ` +
      `(${path.relative(PROJECT, OUT).replace(/\\/g, "/")})\n` +
      `  status: ${JSON.stringify(byStatus)}\n` +
      `  source: paths.maps/systems-inventory.jsonl (${rollups.length} rollup entries)\n`,
  );
}

main();
