#!/usr/bin/env node
"use strict";
/**
 * F9 falsify-refused-rename (BLOCKING tier) — S-OS-06 T3 part 0.
 *
 * After the rename-candidate vs write-permission split, `refusedRenames` is reachable ONLY for a
 * genuine refusal — and a genuine refusal is always RED. Plants a live Class-1 path whose rename
 * would land ON a write-protected (Class-4) path and asserts:
 *   - the dry-run plan records it in refusedRenames (reason target-write-protected), never in
 *     pathRenames, and stdout prints refusedRenames=1;
 *   - `rename-mc.js --apply` exits non-zero naming it, before renaming or rewriting anything;
 *   - the record-trust exit gate's dry-run item (item 4) flips PASS -> FAIL on refusedRenames=1
 *     in the SAME fixture (baseline observed PASS first, so the RED is attributed to the plant).
 *
 *   node --test tests/regression/S-OS-06/falsify-refused-rename.test.js
 */
const FALSIFIER_ID = "F9";

const test = require("node:test");
const assert = require("node:assert");
const fs = require("fs");
const path = require("path");
const H = require("./falsifier-harness");

const ENFORCER_REL = "scripts/checks/record-trust-exit.js";
const RUNNER_REL = "runtime/f9-dry-run-item.js"; // runtime/ is excluded from the fixture's tracked tree

const BANNER = { "src/banner.js": `// ${H.SLUG} banner\n` };
// An existing protected historical directory that a live rename would land in.
const TARGET_DIR_FILES = { "records/mc/2026-ledger.md": "# ledger\na dated record, verbatim\n" };
// Four more generated views so the fixture meets the gate's PRE-apply derived rule (exactly 5 views).
const EXTRA_VIEWS = ["gen/view-a.json", "gen/view-b.json", "gen/view-c.json", "gen/view-d.json"];
const VIEW_FILES = Object.fromEntries(EXTRA_VIEWS.map((v) => [v, `{ "slug": "${H.SLUG}" }\n`]));

const PLANTED_REL = `records/${H.SLUG}/guide.md`;
const PLANTED_TARGET = "records/mc/guide.md";
const PLANTED_BODY = `# the ${H.SLUG} guide\n`;

const RUNNER_SRC = [
  `"use strict";`,
  `const path = require("path");`,
  `const { runRecordTrustExit, exitCodeFor } = require(path.join(__dirname, "..", ...${JSON.stringify(ENFORCER_REL.split("/"))}));`,
  `runRecordTrustExit({ items: ["dry-run"] }).then((results) => {`,
  `  const code = exitCodeFor(results);`,
  `  process.stdout.write(JSON.stringify({ code, detail: results[0] && results[0].detail }));`,
  `  process.exitCode = code;`,
  `});`,
  ``,
].join("\n");

function fixturePartition() {
  return H.basePartition({
    mutate: (p) => {
      p.pathGlobs.push({ pattern: "records/mc/**", class: 4, writeProtected: true, warrant: "fixture dated records, historical" });
      for (const v of EXTRA_VIEWS) p.generatedViews.push({ path: v, class: 1, warrant: "fixture generated view, regenerated by its builder" });
    },
  });
}

const readPlan = (fx) => JSON.parse(fs.readFileSync(path.join(fx.dir, "runtime", "S-OS-06", "rename-plan.json"), "utf8"));

function runGateItem(fx) {
  const r = fx.runNode(RUNNER_REL, []);
  const out = H.json(r);
  assert.strictEqual(r.status, out.code, `runner exit code must equal the gate's exit code: ${r.out}`);
  return out;
}

test(`${FALSIFIER_ID} RED: a live Class-1 path whose rename lands ON a write-protected path -> plan refusedRenames=1, --apply REFUSES (non-zero)`, () => {
  const extraFiles = { ...BANNER, ...TARGET_DIR_FILES, ...VIEW_FILES, [PLANTED_REL]: PLANTED_BODY };
  H.withFixture({ extraFiles, partition: fixturePartition() }, (fx) => {
    const dry = fx.runCodemod(["--dry-run"]);
    assert.match(dry.stdout, /^\s*refusedRenames=1\s*$/m, dry.out);
    const plan = readPlan(fx);
    assert.deepStrictEqual(
      plan.refusedRenames.map((r) => [r.from, r.to, r.reason, r.class]),
      [[PLANTED_REL, PLANTED_TARGET, "target-write-protected", 4]],
      `the plan must record exactly the planted genuine refusal: ${dry.out}`
    );
    assert.ok(!plan.pathRenames.some((r) => r.from === PLANTED_REL), "a refused rename never reaches pathRenames");

    const apply = fx.runCodemod(["--apply"]);
    assert.notStrictEqual(apply.status, 0, `--apply must refuse: ${apply.out}`);
    assert.match(
      apply.stderr,
      /--apply refused: records\/warpos\/guide\.md -> records\/mc\/guide\.md lands on a write-protected path \(class 4, path-glob\)/
    );
    assert.strictEqual(fx.read(PLANTED_REL), PLANTED_BODY, "the planted path is untouched");
    assert.strictEqual(fx.exists(PLANTED_TARGET), false, "nothing landed on the protected path");
    assert.strictEqual(fx.read("src/banner.js"), BANNER["src/banner.js"], "the refusal happens before ANY rewrite");
  });
});

test(`${FALSIFIER_ID} RED (gate): record-trust-exit item 4 is PASS on the clean fixture and FAIL on refusedRenames=1 after the plant`, () => {
  const extraFiles = { ...BANNER, ...TARGET_DIR_FILES, ...VIEW_FILES };
  H.withFixture({ extraFiles, partition: fixturePartition() }, (fx) => {
    fx.write(ENFORCER_REL, fs.readFileSync(path.join(H.REAL_ROOT, ...ENFORCER_REL.split("/")), "utf8"));
    fx.write(RUNNER_REL, RUNNER_SRC);

    const base = runGateItem(fx);
    assert.strictEqual(base.code, 0, `the clean fixture must pass item 4 first (attribution): ${base.detail}`);
    assert.match(base.detail, /refusedRenames=0/);

    fx.write(PLANTED_REL, PLANTED_BODY);
    fx.commit("F9 plant: a live path whose rename lands on a write-protected path", [PLANTED_REL]);

    const red = runGateItem(fx);
    assert.strictEqual(red.code, 1, `the gate must go RED on the planted refusal: ${red.detail}`);
    assert.match(red.detail, /(^|; )refusedRenames=1(;|$)/);
    assert.match(red.detail, /plan refusedRenames=1: records\/warpos\/guide\.md -> records\/mc\/guide\.md \(target-write-protected\)/);
  });
});
