#!/usr/bin/env node
"use strict";
/**
 * F5 falsify-codemod-touches-generated-view (BLOCKING tier) — S-OS-06 T2, AC-1.3 / AC-5.2 / AC-7.3.
 *
 * The codemod never hand-edits a regenerated file. T3 part 0 ruling (rename candidacy vs write
 * permission, beta r1/r3): a generated view whose DIRECTORY is renamed together with live
 * Class-1 paths is MOVED with that directory — a move, not a content rewrite; its content stays
 * DERIVED and byte-identical. A generated view renamed on its own authority (its own file name,
 * or a directory rename no live Class-1 path makes) is still REFUSED — non-zero, naming the
 * write-protected path — before renaming or rewriting anything. A Class-4 historical path is
 * never a rename candidate at all: it keeps its name verbatim (keptHistoricalPaths) and --apply
 * proceeds. GREEN companion: a generated view off every rename path survives a real --apply
 * byte-identical while live content is rewritten, and its occurrences are DERIVED.
 *
 *   node --test tests/regression/S-OS-06/falsify-codemod-touches-generated-view.test.js
 */
const FALSIFIER_ID = "F5";

const test = require("node:test");
const assert = require("node:assert");
const fs = require("fs");
const path = require("path");
const H = require("./falsifier-harness");

const BANNER = { "src/banner.js": `// ${H.SLUG} banner\n` };
const MANIFEST_REL = `_${H.SLUG}/MANIFEST.json`;
const MANIFEST_BODY = `{ "root": "_${H.SLUG}", "files": ["_${H.SLUG}/templates/a.md"] }\n`;
const TEMPLATE_REL = `_${H.SLUG}/templates/a.md`;

const readPlan = (fx) => JSON.parse(fs.readFileSync(path.join(fx.dir, "runtime", "S-OS-06", "rename-plan.json"), "utf8"));
const withView = (viewPath) =>
  H.basePartition({
    mutate: (p) => p.generatedViews.push({ path: viewPath, class: 1, warrant: "fixture manifest, regenerated by its builder" }),
  });

test(`${FALSIFIER_ID} GREEN: a generated view off every rename path survives a real --apply byte-identical; its hits are DERIVED`, () => {
  H.withFixture({ extraFiles: BANNER }, (fx) => {
    const view = fx.read(".claude/paths.json");
    const dry = fx.runCodemod(["--dry-run"]);
    assert.strictEqual(dry.status, 0, dry.out);
    const full = JSON.parse(fs.readFileSync(path.join(fx.dir, "runtime", "S-OS-06", "rename-occurrences.full.json"), "utf8"));
    const viewRows = full.rows.filter((r) => r.file === ".claude/paths.json");
    assert.ok(viewRows.length > 0, "the fixture view must carry the slug (non-vacuous)");
    assert.ok(viewRows.every((r) => r.disposition === "derived"), "generated-view hits are derived, never rewritten or pinned");

    const apply = fx.runCodemod(["--apply"]);
    assert.strictEqual(apply.status, 0, apply.out);
    assert.strictEqual(fx.read(".claude/paths.json"), view, "the generated view must be byte-identical after --apply");
    assert.strictEqual(fx.read("src/banner.js"), "// mc banner\n", "the GREEN apply must really rewrite live content");
  });
});

test(`${FALSIFIER_ID} GREEN: a generated view moving WITH its Class-1 directory rename is a permitted MOVE; its content stays derived, byte-identical`, () => {
  const extraFiles = { ...BANNER, [MANIFEST_REL]: MANIFEST_BODY, [TEMPLATE_REL]: `# ${H.SLUG} template\n` };
  H.withFixture({ extraFiles, partition: withView(MANIFEST_REL) }, (fx) => {
    const dry = fx.runCodemod(["--dry-run"]);
    assert.strictEqual(dry.status, 0, dry.out);
    const plan = readPlan(fx);
    assert.deepStrictEqual(plan.refusedRenames, [], `a generated-view directory move is not a refusal: ${dry.out}`);
    assert.ok(
      plan.pathRenames.some((r) => r.from === MANIFEST_REL && r.to === "_mc/MANIFEST.json" && r.generatedViewMove === true),
      `the move must be planned and marked as a generated-view move: ${JSON.stringify(plan.pathRenames)}`
    );
    assert.match(dry.stdout, /^\s*refusedRenames=0\s*$/m);
    const full = JSON.parse(fs.readFileSync(path.join(fx.dir, "runtime", "S-OS-06", "rename-occurrences.full.json"), "utf8"));
    const viewRows = full.rows.filter((r) => r.file === MANIFEST_REL);
    assert.ok(viewRows.length > 0 && viewRows.every((r) => r.disposition === "derived"), "the moved view's content stays derived");

    const apply = fx.runCodemod(["--apply"]);
    assert.strictEqual(apply.status, 0, apply.out);
    assert.strictEqual(fx.exists(MANIFEST_REL), false, "the view moved out of the renamed directory");
    assert.strictEqual(fx.read("_mc/MANIFEST.json"), MANIFEST_BODY, "a MOVE, not a content rewrite: the view is byte-identical");
    assert.strictEqual(fx.read("_mc/templates/a.md"), "# mc template\n", "the live Class-1 sibling moved and was rewritten");
    assert.strictEqual(fx.read("src/banner.js"), "// mc banner\n");

    // T3 post-apply view identity: a SECOND dry-run over the applied tree resolves the moved view to its
    // declared entry — its hits stay DERIVED at the new path (never re-planned as rewritten), nothing is
    // refused, no rename remains, and a second --apply is a no-op (AC-1.2 idempotency across a view move).
    const again = fx.runCodemod(["--dry-run"]);
    assert.strictEqual(again.status, 0, again.out);
    const plan2 = readPlan(fx);
    assert.deepStrictEqual(plan2.refusedRenames, [], `the moved view is not refused on a re-run: ${again.out}`);
    assert.deepStrictEqual(plan2.pathRenames, [], `no rename remains after the apply: ${JSON.stringify(plan2.pathRenames)}`);
    const full2 = JSON.parse(fs.readFileSync(path.join(fx.dir, "runtime", "S-OS-06", "rename-occurrences.full.json"), "utf8"));
    const movedRows = full2.rows.filter((r) => r.file === "_mc/MANIFEST.json");
    assert.ok(
      movedRows.length > 0 && movedRows.every((r) => r.disposition === "derived"),
      `the moved view stays derived at its post-rename path: ${JSON.stringify(movedRows.slice(0, 3))}`
    );
    assert.strictEqual(full2.rows.filter((r) => r.disposition === "rewritten").length, 0, "nothing is left to rewrite after the apply");
    const reapply = fx.runCodemod(["--apply"]);
    assert.strictEqual(reapply.status, 0, reapply.out);
    assert.match(reapply.stdout, /renamed=0 filesRewritten=0/);
    assert.strictEqual(fx.read("_mc/MANIFEST.json"), MANIFEST_BODY, "the re-apply never touches the moved view");
  });
});

test(`${FALSIFIER_ID} RED: a generated view on a rename path with NO Class-1 directory rename to follow -> --apply REFUSES (non-zero), nothing renamed or rewritten`, () => {
  H.withFixture({ extraFiles: { ...BANNER, [MANIFEST_REL]: MANIFEST_BODY }, partition: withView(MANIFEST_REL) }, (fx) => {
    const apply = fx.runCodemod(["--apply"]);
    assert.notStrictEqual(apply.status, 0, `--apply must refuse: ${apply.out}`);
    assert.match(apply.stderr, /--apply refused: .*MANIFEST\.json -> _mc\/MANIFEST\.json is write-protected \(class 1, generated-view\)/);
    assert.strictEqual(fx.read(MANIFEST_REL), MANIFEST_BODY, "the generated view is untouched");
    assert.strictEqual(fx.exists("_mc/MANIFEST.json"), false, "the generated view was not renamed");
    assert.strictEqual(fx.read("src/banner.js"), BANNER["src/banner.js"], "the refusal happens before ANY rewrite");

    const dry = fx.runCodemod(["--dry-run"]);
    const plan = readPlan(fx);
    assert.ok(
      plan.refusedRenames.some(
        (r) => r.from === MANIFEST_REL && r.kind === "generated-view" && r.reason === "generated-view-move-without-class1-dir-rename"
      ),
      `the plan must record the refusal: ${dry.out}`
    );
    assert.ok(!plan.pathRenames.some((r) => r.from === MANIFEST_REL), "a refused view never reaches pathRenames");
  });
});

test(`${FALSIFIER_ID} RED: a generated view whose OWN file name would be renamed (not a directory move) -> --apply REFUSES`, () => {
  const rel = `.claude/${H.SLUG}-views.json`;
  const body = `{ "slug": "${H.SLUG}" }\n`;
  H.withFixture({ extraFiles: { ...BANNER, [rel]: body }, partition: withView(rel) }, (fx) => {
    const apply = fx.runCodemod(["--apply"]);
    assert.notStrictEqual(apply.status, 0, `--apply must refuse: ${apply.out}`);
    assert.match(apply.stderr, /--apply refused: \.claude\/warpos-views\.json -> \.claude\/mc-views\.json is write-protected \(class 1, generated-view\)/);
    assert.strictEqual(fx.read(rel), body);
    assert.strictEqual(fx.exists(".claude/mc-views.json"), false);
    assert.strictEqual(fx.read("src/banner.js"), BANNER["src/banner.js"], "the refusal happens before ANY rewrite");
  });
});

test(`${FALSIFIER_ID} GREEN: a Class-4 historical path on a rename path is KEPT verbatim (never a rename candidate); --apply proceeds`, () => {
  const rel = `history/${H.SLUG}/old.md`;
  const body = `the ${H.SLUG} record\n`;
  H.withFixture({ extraFiles: { ...BANNER, [rel]: body } }, (fx) => {
    const dry = fx.runCodemod(["--dry-run"]);
    assert.strictEqual(dry.status, 0, dry.out);
    const plan = readPlan(fx);
    assert.ok(
      plan.keptHistoricalPaths.some((k) => k.path === rel && k.class === 4 && k.wouldBe === "history/mc/old.md"),
      `the historical path must be recorded as kept: ${JSON.stringify(plan.keptHistoricalPaths)}`
    );
    assert.strictEqual(plan.keptHistoricalPathCount, plan.keptHistoricalPaths.length);
    assert.ok(!plan.pathRenames.some((r) => r.from === rel), "a historical path is never a rename candidate");
    assert.ok(!plan.refusedRenames.some((r) => r.from === rel), "a historical path is not a refusal either");
    assert.match(dry.stdout, /^\s*keptHistoricalPaths=1\s*$/m);

    const apply = fx.runCodemod(["--apply"]);
    assert.strictEqual(apply.status, 0, apply.out);
    assert.strictEqual(fx.read(rel), body, "the historical record keeps its name AND bytes");
    assert.strictEqual(fx.exists("history/mc/old.md"), false);
    assert.strictEqual(fx.read("src/banner.js"), "// mc banner\n", "the apply really ran over live content");
  });
});
