#!/usr/bin/env node
"use strict";
/**
 * F5 falsify-codemod-touches-generated-view (BLOCKING tier) — S-OS-06 T2, AC-1.3 / AC-5.2 / AC-7.3.
 *
 * The codemod never hand-edits a regenerated file. Plants a generated view (and, as a
 * sibling, a Class-4 historical path) where the rename rules WOULD move it, and asserts
 * `rename-mc.js --apply` REFUSES — non-zero, naming the write-protected path — before
 * renaming or rewriting anything. GREEN companion: a generated view off every rename path
 * survives a real --apply byte-identical while live content is rewritten, and its
 * occurrences are DERIVED, never in the rewrite plan.
 *
 *   node --test tests/regression/S-OS-06/falsify-codemod-touches-generated-view.test.js
 */
const FALSIFIER_ID = "F5";

const test = require("node:test");
const assert = require("node:assert");
const fs = require("fs");
const path = require("path");
const H = require("./falsifier-harness");

const BANNER = { "src/banner.js": `// ${H.SLUG} banner\n` };
const MANIFEST_REL = `_${H.SLUG}/MANIFEST.json`;
const MANIFEST_BODY = `{ "root": "_${H.SLUG}", "files": ["_${H.SLUG}/templates/a.md"] }\n`;

test(`${FALSIFIER_ID} GREEN: a generated view off every rename path survives a real --apply byte-identical; its hits are DERIVED`, () => {
  H.withFixture({ extraFiles: BANNER }, (fx) => {
    const view = fx.read(".claude/paths.json");
    const dry = fx.runCodemod(["--dry-run"]);
    assert.strictEqual(dry.status, 0, dry.out);
    const full = JSON.parse(fs.readFileSync(path.join(fx.dir, "runtime", "S-OS-06", "rename-occurrences.full.json"), "utf8"));
    const viewRows = full.rows.filter((r) => r.file === ".claude/paths.json");
    assert.ok(viewRows.length > 0, "the fixture view must carry the slug (non-vacuous)");
    assert.ok(viewRows.every((r) => r.disposition === "derived"), "generated-view hits are derived, never rewritten or pinned");

    const apply = fx.runCodemod(["--apply"]);
    assert.strictEqual(apply.status, 0, apply.out);
    assert.strictEqual(fx.read(".claude/paths.json"), view, "the generated view must be byte-identical after --apply");
    assert.strictEqual(fx.read("src/banner.js"), "// mc banner\n", "the GREEN apply must really rewrite live content");
  });
});

test(`${FALSIFIER_ID} RED: a generated view on a rename path -> --apply REFUSES (non-zero), nothing renamed or rewritten`, () => {
  const partition = H.basePartition({
    mutate: (p) => p.generatedViews.push({ path: MANIFEST_REL, class: 1, warrant: "fixture manifest, regenerated by its builder" }),
  });
  H.withFixture({ extraFiles: { ...BANNER, [MANIFEST_REL]: MANIFEST_BODY }, partition }, (fx) => {
    const apply = fx.runCodemod(["--apply"]);
    assert.notStrictEqual(apply.status, 0, `--apply must refuse: ${apply.out}`);
    assert.match(apply.stderr, /--apply refused: .*MANIFEST\.json -> _mc\/MANIFEST\.json is write-protected \(class 1, generated-view\)/);
    assert.strictEqual(fx.read(MANIFEST_REL), MANIFEST_BODY, "the generated view is untouched");
    assert.strictEqual(fx.exists("_mc/MANIFEST.json"), false, "the generated view was not renamed");
    assert.strictEqual(fx.read("src/banner.js"), BANNER["src/banner.js"], "the refusal happens before ANY rewrite");

    const dry = fx.runCodemod(["--dry-run"]);
    const plan = JSON.parse(fs.readFileSync(path.join(fx.dir, "runtime", "S-OS-06", "rename-plan.json"), "utf8"));
    assert.ok(
      plan.refusedRenames.some((r) => r.from === MANIFEST_REL && r.kind === "generated-view"),
      `the plan must record the refusal: ${dry.out}`
    );
    assert.ok(!plan.pathRenames.some((r) => r.from === MANIFEST_REL), "a write-protected view never reaches pathRenames");
  });
});

test(`${FALSIFIER_ID} RED: a Class-4 historical path on a rename path -> --apply refuses the same way`, () => {
  const rel = `history/${H.SLUG}/old.md`;
  H.withFixture({ extraFiles: { ...BANNER, [rel]: `the ${H.SLUG} record\n` } }, (fx) => {
    const apply = fx.runCodemod(["--apply"]);
    assert.notStrictEqual(apply.status, 0, `--apply must refuse: ${apply.out}`);
    assert.match(apply.stderr, /is write-protected \(class 4, path-glob\)/);
    assert.strictEqual(fx.exists(rel), true);
    assert.strictEqual(fx.read("src/banner.js"), BANNER["src/banner.js"]);
  });
});
