/**
 * Shared path utilities for hook scripts.
 *
 * Solves the Windows path normalization bug: CLAUDE_PROJECT_DIR may be
 * unset (defaults to "."), but Claude Code sends absolute Windows paths
 * like C:\Users\...\file.ts. Without path.resolve(), startsWith() fails
 * and all path-based matching breaks silently.
 *
 * Usage:
 *   const { PROJECT, relPath } = require("./lib/paths");
 */

const path = require("path");
const fs = require("fs");

const PROJECT = path.resolve(process.env.CLAUDE_PROJECT_DIR || ".");

// ── Centralized path registry ──────────────────────────────
// All hooks read paths from .claude/paths.json (generated by scripts/paths/build.js
// from framework/paths.registry.json). To move a folder, edit the registry, run
// build.js, commit all generated artifacts together. The fallback below now
// loads from paths.generated.js (also built by the same generator) so the
// hand-duplicated table that used to live here is closed as a source of fork.
let PATHS = {};
try {
  const raw = JSON.parse(
    fs.readFileSync(path.join(PROJECT, ".claude", "paths.json"), "utf8"),
  );
  PATHS = Object.fromEntries(
    Object.entries(raw)
      .filter(([k]) => k !== "version" && k !== "$schema")
      .map(([k, v]) => [k, path.join(PROJECT, v)]),
  );
} catch {
  // Fallback path 1: load from paths.generated.js (built by scripts/paths/build.js
  // from framework/paths.registry.json). Same shape as paths.json but ships in the
  // hook lib so paths resolve even if .claude/paths.json was deleted.
  try {
    PATHS = require("./paths.generated").PATHS;
  } catch {
    // Fallback path 2: hardcoded defaults. Only hit if both paths.json AND
    // paths.generated.js are absent (e.g. fresh install before first build).
    // Keep this small subset alive for the bare-bootstrap case.
    PATHS = LEGACY_FALLBACK_PATHS();
  }
}

// S-OS-06 T3 4c: a registry path under `_mc/` or `.mc/` resolves to the canonical location when it exists, else to
// an EXISTING legacy-named twin IN PLACE (one release; never moved; one deprecation line per process). Every other
// key is untouched (zero filesystem cost). Fail-open: a helper failure leaves the canonical joins as they were.
try {
  const mcDirs = require("./mc-dirs");
  for (const [key, value] of Object.entries(PATHS)) {
    if (typeof value !== "string") continue;
    const rel = path.relative(PROJECT, value);
    if (!mcDirs.legacySegment(rel.split(/[\\/]+/)[0])) continue;
    PATHS[key] = mcDirs.resolveProjectPath(PROJECT, rel);
  }
} catch {
  /* fail-open: path resolution must never break a hook */
}

function LEGACY_FALLBACK_PATHS() {
  return {
    events: path.join(PROJECT, ".claude", "project", "events"),
    memory: path.join(PROJECT, ".claude", "project", "memory"),
    maps: path.join(PROJECT, ".claude", "project", "maps"),
    reference: path.join(PROJECT, ".claude", "project", "reference"),
    runtime: path.join(PROJECT, ".claude", "runtime"),
    logs: path.join(PROJECT, ".claude", "runtime", "logs"),
    handoffs: path.join(PROJECT, ".claude", "runtime", "handoffs"),
    handoffLatest: path.join(PROJECT, ".claude", "runtime", "handoff.md"),
    plans: path.join(PROJECT, ".claude", "runtime", "plans"),
    agents: path.join(PROJECT, ".claude", "agents"),
    agentSystem: path.join(PROJECT, ".claude", "agents", "president", ".system"),
    betaSystem: path.join(
      PROJECT,
      ".claude",
      "agents",
      "president",
      ".system",
      "beta",
    ),
    commands: path.join(PROJECT, ".claude", "commands"),
    content: path.join(PROJECT, ".claude", "content"),
    dreams: path.join(PROJECT, ".claude", "dreams"),
    favorites: path.join(PROJECT, ".claude", "content", "favorites"),
    hooks: path.join(PROJECT, "scripts", "hooks"),
    hookLib: path.join(PROJECT, "scripts", "hooks", "lib"),
    patterns: path.join(PROJECT, "patterns"),
    requirements: path.join(PROJECT, "requirements"),
    manifest: path.join(PROJECT, ".claude", "manifest.json"),
    settings: path.join(PROJECT, ".claude", "settings.json"),
    store: path.join(PROJECT, ".claude", "agents", "store.json"),
    oneshotStore: path.join(
      PROJECT,
      ".claude",
      "agents",
      "president",
      ".system",
      "oneshot",
      "store.json",
    ),
    eventsFile: path.join(
      PROJECT,
      ".claude",
      "project",
      "events",
      "events.jsonl",
    ),
    toolsFile: path.join(
      PROJECT,
      ".claude",
      "project",
      "events",
      "tools.jsonl",
    ),
    requirementsFile: path.join(
      PROJECT,
      ".claude",
      "project",
      "events",
      "requirements.jsonl",
    ),
    requirementsStagedFile: path.join(
      PROJECT,
      ".claude",
      "project",
      "events",
      "requirements-staged.jsonl",
    ),
    learningsFile: path.join(
      PROJECT,
      ".claude",
      "project",
      "memory",
      "learnings.jsonl",
    ),
    tracesFile: path.join(
      PROJECT,
      ".claude",
      "project",
      "memory",
      "traces.jsonl",
    ),
    systemsFile: path.join(
      PROJECT,
      ".claude",
      "project",
      "memory",
      "systems.jsonl",
    ),
    specGraph: path.join(
      PROJECT,
      ".claude",
      "project",
      "maps",
      "SPEC_GRAPH.json",
    ),
    judgmentModel: path.join(
      PROJECT,
      ".claude",
      "agents",
      "president",
      ".system",
      "beta",
      "judgement-model.md",
    ),
    judgmentRecommendations: path.join(
      PROJECT,
      ".claude",
      "agents",
      "president",
      ".system",
      "beta",
      "judgement-model-recommendations.md",
    ),
    betaSourceData: path.join(
      PROJECT,
      ".claude",
      "agents",
      "president",
      ".system",
      "beta",
      "mined",
      "beta-source-data.md",
    ),
    betaEvents: path.join(
      PROJECT,
      ".claude",
      "agents",
      "president",
      ".system",
      "beta",
      "events.jsonl",
    ),
    lexicon: path.join(
      PROJECT,
      ".claude",
      "agents",
      "president",
      ".system",
      "lexicon.md",
    ),
    pathsLib: path.join(PROJECT, "scripts", "hooks", "lib", "paths.js"),
    loggerLib: path.join(PROJECT, "scripts", "hooks", "lib", "logger.js"),
  };
}

/**
 * Convert an absolute file path to a project-relative path with forward slashes.
 * Handles Windows backslashes, absolute paths, and the unset CLAUDE_PROJECT_DIR case.
 *
 * @param {string} filePath - Absolute or relative file path from Claude Code
 * @returns {string} Relative path with forward slashes (e.g., "scripts/hooks/edit-watcher.js")
 */
function relPath(filePath) {
  // Defensive: callers that forget the upstream `if (!filePath) exit(0)`
  // guard would otherwise crash with "Path must be a string, received
  // undefined" from path.resolve. Returning "" lets callers' downstream
  // string ops (startsWith/match/etc.) no-op cleanly. Source: RT-009.
  if (filePath == null || typeof filePath !== "string") return "";
  const abs = path.resolve(filePath);
  const proj = path.resolve(PROJECT);
  if (abs.startsWith(proj)) {
    return abs
      .slice(proj.length)
      .replace(/^[/\\]+/, "")
      .replace(/\\/g, "/");
  }
  return abs.replace(/\\/g, "/");
}

module.exports = { PROJECT, relPath, PATHS };
