#!/usr/bin/env node

/**
 * scripts/paths/build.js — generate path artifacts from framework/paths.registry.json
 *
 * Inputs:
 *   framework/paths.registry.json   (single source of truth)
 *
 * Outputs:
 *   .claude/paths.json                              (flat key→string, runtime consumer)
 *   scripts/hooks/lib/paths.generated.js            (fallback when paths.json missing)
 *   scripts/path-lint.rules.generated.json          (regex arrays for path-lint critical+warn)
 *   schemas/paths.schema.json                       (JSONSchema validator for paths.json)
 *   _requirements/03-architecture/PATH_KEYS.md               (human reference table)
 *
 * Run:
 *   node scripts/paths/build.js                     (regenerate all)
 *   node scripts/paths/build.js --check             (exit 1 if any artifact stale)
 *
 * Phase 1B per BACKLOG §1.
 */

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = path.resolve(__dirname, "..", "..");
const REGISTRY_FILE = path.join(ROOT, "framework", "paths.registry.json");
const CHECK_MODE = process.argv.includes("--check");

const OUT_PATHS_JSON = path.join(ROOT, ".claude", "paths.json");
const OUT_GENERATED_JS = path.join(
  ROOT,
  "scripts",
  "hooks",
  "lib",
  "paths.generated.js",
);
const OUT_LINT_RULES = path.join(
  ROOT,
  "scripts",
  "path-lint.rules.generated.json",
);
const OUT_SCHEMA = path.join(ROOT, "schemas", "paths.schema.json");
const OUT_DOC = path.join(
  ROOT,
  "_requirements",
  "03-architecture",
  "PATH_KEYS.md",
);

function readRegistry() {
  const raw = fs.readFileSync(REGISTRY_FILE, "utf8");
  const reg = JSON.parse(raw);
  if (reg.$schema !== "mc/paths-registry/v1") {
    throw new Error(`Unexpected registry $schema: ${reg.$schema}`);
  }
  return reg;
}

function buildPathsJson(registry) {
  // Phase 2E: $schema first so loaders can detect format version cheaply.
  const out = {
    $schema: "mc/paths/v" + registry.version,
    version: registry.version,
  };
  for (const [key, entry] of Object.entries(registry.paths)) {
    if (entry.removedIn) continue;
    out[key] = entry.path;
  }
  return out;
}

function buildGeneratedJs(registry) {
  const entries = Object.entries(registry.paths)
    .filter(([, entry]) => !entry.removedIn)
    .map(([key, entry]) => {
      const segments = entry.path
        .split("/")
        .map((s) => JSON.stringify(s))
        .join(", ");
      return `  ${JSON.stringify(key)}: path.join(PROJECT, ${segments})`;
    });

  return `// AUTO-GENERATED by scripts/paths/build.js. Do not edit by hand.
// Source: framework/paths.registry.json
// Regenerate: node scripts/paths/build.js
//
// This module exports an absolute-path PATHS table used by hooks when
// .claude/paths.json is missing or unreadable. Pre-Phase-1B this table
// was hand-duplicated inside scripts/hooks/lib/paths.js — that fork is
// now closed; lib/paths.js reads from here.

const path = require("path");

const PROJECT = path.resolve(process.env.CLAUDE_PROJECT_DIR || ".");

const PATHS = {
${entries.join(",\n")}
};

module.exports = { PROJECT, PATHS };
`;
}

function buildLintRules(registry) {
  const critical = registry.lintRules.critical;
  const warn = [];
  for (const key of registry.lintRules.warnKeys) {
    const entry = registry.paths[key];
    if (!entry) continue;
    const escaped = entry.path.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    warn.push({ match: escaped, key });
  }
  return {
    $schema: "mc/path-lint-rules/v1",
    generated_by: "scripts/paths/build.js",
    critical,
    warn,
    skipSubstrings: registry.skipSubstrings,
    skipDirs: registry.skipDirs,
  };
}

function buildSchema(registry) {
  const properties = {
    $schema: { type: "string", const: "mc/paths/v" + registry.version },
    version: { type: "integer", const: registry.version },
  };
  for (const [key, entry] of Object.entries(registry.paths)) {
    if (entry.removedIn) continue;
    properties[key] = {
      type: "string",
      const: entry.path,
      description: `${entry.kind} (${entry.owner}) — ${entry.docsToken || `paths.${key}`}`,
    };
  }
  return {
    $schema: "http://json-schema.org/draft-07/schema#",
    $id: "mc/paths/v" + registry.version,
    title: "MC paths.json",
    type: "object",
    required: ["$schema", "version"],
    additionalProperties: false,
    properties,
  };
}

function buildDoc(registry) {
  const lines = [];
  lines.push("# Path Keys Reference");
  lines.push("");
  lines.push(
    "> AUTO-GENERATED by `scripts/paths/build.js`. Source of truth: `framework/paths.registry.json`. Do not edit by hand — edit the registry, run the build.",
  );
  lines.push("");
  lines.push(
    "Markdown convention: reference paths as `paths.X` in prose. Code: `const { PATHS } = require('./lib/paths'); PATHS.X`. Renames flow through the registry; consumers follow automatically.",
  );
  lines.push("");
  lines.push("## Active path keys");
  lines.push("");
  lines.push("| Key | Path | Kind | Owner | Mutable | Introduced | Notes |");
  lines.push("|---|---|---|---|---|---|---|");

  const entries = Object.entries(registry.paths)
    .filter(([, e]) => !e.removedIn)
    .sort(([a], [b]) => a.localeCompare(b));

  for (const [key, entry] of entries) {
    const note = entry.replaces
      ? `replaces \`${entry.replaces}\``
      : entry._note
        ? entry._note.split("\n")[0].slice(0, 60)
        : "";
    lines.push(
      `| \`${key}\` | \`${entry.path}\` | ${entry.kind} | ${entry.owner} | ${entry.mutable ? "yes" : "no"} | ${entry.introducedIn} | ${note} |`,
    );
  }

  const removed = Object.entries(registry.paths).filter(([, e]) => e.removedIn);
  if (removed.length > 0) {
    lines.push("");
    lines.push("## Removed path keys");
    lines.push("");
    lines.push("| Key | Path | Removed in | Replaces |");
    lines.push("|---|---|---|---|");
    for (const [key, entry] of removed) {
      lines.push(
        `| \`${key}\` | \`${entry.path}\` | ${entry.removedIn} | ${entry.replaces || "—"} |`,
      );
    }
  }

  lines.push("");
  lines.push("## Owner classification");
  lines.push("");
  lines.push(
    "- **framework** — shipped by MC. `/mc:update` may regenerate or merge.",
  );
  lines.push(
    "- **generated** — produced by tooling. Do not hand-edit; regenerate from source.",
  );
  lines.push(
    "- **runtime** — written by sessions during normal operation. Excluded from publish.",
  );
  lines.push(
    "- **project** — owned by the user/team. Never overwritten by `/mc:update`.",
  );
  lines.push("");
  lines.push("## Mutability");
  lines.push("");
  lines.push(
    "`mutable: true` keys are written during runtime and excluded from release scrubbing. `mutable: false` keys are read-only at runtime; edit-watcher flags writes.",
  );
  lines.push("");

  return lines.join("\n") + "\n";
}

function sha256(s) {
  return crypto.createHash("sha256").update(s).digest("hex").slice(0, 12);
}

function ensureDir(file) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
}

function writeIfChanged(file, content) {
  ensureDir(file);
  let prior = "";
  try {
    prior = fs.readFileSync(file, "utf8");
  } catch {
    /* didn't exist */
  }
  if (prior === content) return { changed: false, file };
  if (CHECK_MODE) {
    return { changed: true, file, stale: true };
  }
  fs.writeFileSync(file, content);
  return { changed: true, file };
}

function fmtJson(obj) {
  return JSON.stringify(obj, null, 2) + "\n";
}

function main() {
  const registry = readRegistry();

  const targets = [
    { file: OUT_PATHS_JSON, content: fmtJson(buildPathsJson(registry)) },
    { file: OUT_GENERATED_JS, content: buildGeneratedJs(registry) },
    { file: OUT_LINT_RULES, content: fmtJson(buildLintRules(registry)) },
    { file: OUT_SCHEMA, content: fmtJson(buildSchema(registry)) },
    { file: OUT_DOC, content: buildDoc(registry) },
  ];

  const results = targets.map((t) => writeIfChanged(t.file, t.content));
  const stale = results.filter((r) => r.stale);

  console.log(`\nscripts/paths/build.js — registry v${registry.version}`);
  for (const r of results) {
    const rel = path.relative(ROOT, r.file).replace(/\\/g, "/");
    if (CHECK_MODE) {
      console.log(`  ${r.stale ? "STALE" : "ok   "}  ${rel}`);
    } else if (r.changed) {
      console.log(`  wrote  ${rel}`);
    } else {
      console.log(`  ok     ${rel}`);
    }
  }

  if (CHECK_MODE && stale.length > 0) {
    console.error(
      `\n${stale.length} artifact(s) stale. Run: node scripts/paths/build.js`,
    );
    process.exit(1);
  }
}

main();
